# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------

#Text
title: MODI

icon: /assets/img/Micon.png

#Links
modi_icon_link: https://modiproject.eu/
linkedin_icon_link: https://www.linkedin.com/company/modi-project/?originalSubdomain=no
twitter_icon_link: https://twitter.com/MODI_CCAM
youtube_icon_link: https://www.youtube.com/@modi_project
source_code_link: https://github.com/modi-data/modi-data.github.io

#Assets
modi_icon: "assets/img/MODIicon.png"
linkedin_icon: "assets/img/linkedinicon.png"
twitter_icon: "assets/img/twittericon.png"
youtube_icon: "assets/img/youtubeicon.png"
github_icon: "assets/img/githubicon.png"

#scripts
searchMetadata: "scripts/searchMetadata.js"
searchStakeholder: "scripts/searchStakeholder.js"
homeScript: "scripts/home.js"
detailsMetadata: "scripts/detailsMetadata.js"
detailsStakeholder: "scripts/detailsStakeholder.js"

# -----------------------------------------------------------------------------
# Style settings
# -----------------------------------------------------------------------------

#Width that the content of a page is in contained
max_width: 1000px;

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Includes & excludes
include: ['_pages', 'node_modules', 'scripts']

exclude: []

# -----------------------------------------------------------------------------
# Library versions and settings
# -----------------------------------------------------------------------------

#sql.js wasm location
sql-js: "https://sql.js.org/dist/sql-wasm.js"
sql-wasm: "https://sql.js.org/dist/sql-wasm.wasm"

bootstrap:
  version: "5.2.3"
  integrity:
    css: "sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65"
    js: "sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"

# -----------------------------------------------------------------------------
# Database settings
# -----------------------------------------------------------------------------

db-file: 'metadata.sqlite3'