# config.yml

backend:
  name: github
  repo: modi-data/modi-data.github.io
  branch: main
media_folder: 'assets/uploads'
collections:
  - name: 'dbFile'
    label: 'metadata'
    folder: 'dbFiles/'
    fields:
      - { name: Title }