# config.yml

backend:
  name: git-gateway
  branch: livecms
media_folder: 'assets/uploads'
collections:
  - name: 'dbFile'
    label: 'metadata'
    folder: 'dbFiles/'
    fields:
      - { name: Title }